---
type: post
section: "employment-rates//"
weight: 100
title: "Employment"
summary: "Female employment %"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Libraries
library(kableExtra)

```

```{r include=FALSE}
getRepoWorkingDirectory <-  function()
{
  repo_root_dir = Sys.getenv("GITHUB_WORKING_DIR", unset = "GITHUB_WORKING_DIR_NOT_SET")
  
  if (repo_root_dir == "GITHUB_WORKING_DIR_NOT_SET")
  {
    dir_of_this_file <- dirname(rstudioapi::getSourceEditorContext()$path)
    repo_root_dir = paste(dir_of_this_file, "/../../..", sep = "")
  }
  
  return(repo_root_dir)
}
```

```{r include=FALSE}
# Create dataframe
path_to_csv_file <- paste(getRepoWorkingDirectory(), "/CSVs/employment_rates_test1.csv", sep = "")

df_employment <- read.csv(path_to_csv_file)

colnames(df_employment) <- c("Month", "Female employment (%)", "Male employment (%)")
```

# Test H1 2

{{< details "More information" >}}
The details component allows you to hide more detailed information 
that might be relevant to only some users.
{{< /details >}}

## The female employment rate was 72.1% in May 2023

Female and male employment rates in the UK (aged 16 to 64, seasonally adjusted)

## Employment rates, January 2020 to May 2023

```{r echo=FALSE}
knitr::kable(df_employment,
             table.attr = "style=\"width: fit-content;\"")
```
